### ISSUE TITLE
clarify UTF8-ness of VINT

### ISSUE THREAD

**Issue by dericed** [cellar-wg/ebml-specification#198]
From https://mailarchive.ietf.org/arch/msg/cellar/ZeTFBMZ_acBakwYFGZlhM-XJ5yU

Regarding: https://tools.ietf.org/html/draft-ietf-cellar-ebml-08#section-5

> §5: Please elaborate on how this is similar to UTF8. I assume this refers to using prefix bits to indicate the field length. UTF8 does that to maintain backwards compatibility with Ascii. What is the design motivation for using that approach for EBML, which I presume doesn't have such a requirement?

**Comment by robUx4** [comment]
We agreed to remove it in #203
