### ISSUE TITLE
AD review

### ISSUE THREAD

**Issue by dericed** [cellar-wg/ebml-specification#209]
Here's the part of the AD review that is not (yet) addressed in a pull request or any known work.

The Shepherd Report says "There are minor nits to be resolved (adding one RFC 2119 keyword and some schema  attributes which are mentioned but not defined."

Do that comment still apply? To be clear, those are more than nits. Adding a 2119 keyword is substantive change that needs to be agreed to but the working group. Undefined attributes suggest that the draft is incomplete. If the comment is still accurate, then these need to be fixed prior to progressing the draft. If it is not accurate, then I ask the shepherd to please update the shepherd report.

§6:
- "The "VINT_DATA" component of the "Element ID" MUST
NOT be either defined or written as either all zero values or all one
values."
Why?

§8.7: "In this case, the "EBML Reader" should skip data
until a valid..."
Should that be a normative statement? If so, why should and not MUST?

§8.8: If the EBML reader does not interpret Binary Elements, why add them at all? What does interpret them? is the point that the EBML reader treats Binary Elements as opaque, and just hands them to the application?

§10.1.3: "NOT RECOMMENDED" seems overly strong, especially in light of the MAY in the first paragraph. Is the point to say "MUST NOT... except when the implementation needs to update an element without rewriting the entire document"? 

§11: "An "EBML Document" consists of "EBML Elements" and MUST
NOT contain any data that is not part of an "EBML Element"."

That contradicts text in §8.7 that says you can do this in streaming use cases.

§13.1: "The "DocType"
value for an "EBML Document Type" SHOULD be unique and persistent."

What is the scope of uniqueness? How should it be achieved? Is there an expectation to register Document Types?  (Also, why not MUST)?

§13.1.4.1: Are there uniqueness requirements for name?

§13.1.4.2: 
- The idea behind "path" needs elaboration. I'd like to see some high-level discussion of how you indicate where an element is allowed, and how you encode the structure. An example (local to the section) would be helpful.

§13.1.4.4:
- "The "minOccurs" value MUST be
equal to the "EBMLMinOccurrence" value of the "path"."

Why have both if they have to be the same? (Same question for §13.1.4.5)

§13.1.4.12:
- "If the "recurring" attribute
is not present then the "EBML Element" MUST be considered to NOT be
an "Identically Recurring Element"."

"be considered to" is vague for a MUST. What concrete action must implementations take in this case?

§13.1.6.2:
- It seems likely readers will confuse "type" with "data type". Would it be reasonable to call this "document-type" or something similar?

§13.1.10:
- Please state (and cite) which XML schema format is used here.

- Has the schema been mechanically verified?

§13.3.1:
- "The CRC value MUST be computed on a little
endian bitstream and MUST use little endian storage."

Please elaborate. Most elements have been big-endian so far. Do there have to be converted to calculate the CRC?

§15.1:
- "The numbers 0x3FFF and 0x4000 are RESERVED.", "The numbers 0x1FFFFF and 0x200000 are RESERVED.", and "The numbers 0xFFFFFFF and 0x1000000 are RESERVED."
What is the purpose of reserving them?

- "Four octet Element IDs whose lower three octets (as
encoded) would make printable 7-bit ASCII values may be allocated
only Specification Required."

Can you state a range or a list? Don't make IANA judge which values are printable.

§15.2: 
- "The strings may be allocated according to
First Come First Served"

Is there a requirement to register them, or is this optional?

*** Editorial Comments and Nits ***

- General: The draft puts double quotes around every mention of terms that it defines. That is unconventional for IETF documents. I personally find that it makes the draft harder to read. I suggest quoting them on the first mention, then just capitalizing them in subsequent mentions.

§11.1:
- Is the concept of a file concrete (in the sense of a unit of persistent storage) or abstract (as in any stream of data)? I had assumed the latter, but with the different rules about data outside of EBML elements for "files" and "streaming applications", I am not so sure. If you mean "file" concretely, does there need to be additional text in this section describing the structure for streaming applications?

- "The "EBMLElementOccurrence" part is interpreted as an ABNF Variable
Repetition.

I don't understand what that means. There won't be ABNF in an actual schema, will there? (Same for "VariableParentOccurrence”)

- ""EBML Elements" with "EBMLMinOccurrence" set to "1" that also have a
"default" value (see Section 13.1.4.8) declared are not REQUIRED to
be stored but are REQUIRED to be interpreted,"

Statement of fact?

§13.1.4.7
- The attribute is called "size" but defined to be "length". Why not call it length? (Or describe it as "size")?

**Comment by mcr** [comment]
Dave Rice <notifications@github.com> wrote:
    > Would it be acceptable to add some scoping language to the effect of
    > "EBML is used by Matroska[citation] and FFV1[citation]. It MAY be used
    > for use cases similar to those. The applicability of EBML for other use
    > cases is beyond the scope of this document”.

Yes, that's appropriate.

**Comment by dericed** [comment]
Hi @mcr, I believe that one was resolved in https://github.com/Matroska-Org/ebml-specification/pull/199/files?short_path=01f3b0f#diff-01f3b0f2fbf3e44327e6072f64ddc8a0. I'm going to edit the list above to remove it.

**Comment by robUx4** [comment]
@dericed could you check `Please state (and cite) which XML schema format is used here.` ? I'm not sure what to do with that or if it was "mechanically verified"

**Comment by mcr** [comment]
> @dericed could you check `Please state (and cite) which XML schema format is used here.` ? I'm not sure what to do with that or if it was "mechanically verified"

 11.1.11.  XML Schema for EBML Schema (Dave volunteers to complete this)
    The following "XSD" definition is in <FORMAT> (add W3C citation), and can be used to validate an EBML Schema using <TOOL>

**Comment by dericed** [comment]
@robUx4 you may be more aware of the status of this issue than I, was the xml schema comment the only remaining point within this issue?

**Comment by dericed** [comment]
I merged in the xml schema description which IIUC was the last issue in this thread. Feel free to re open if anything here remains.
