### ISSUE TITLE
Problems with the EBML Element ID Registry

### ISSUE THREAD

**Issue by mkver** [cellar-wg/ebml-specification#222]
I just read the [CELLAR EBML Element ID Registry part](https://github.com/Matroska-Org/ebml-specification/blob/master/specification.markdown#cellar-ebml-element-id-registry) and have fundamental objections to the process described therein.

What would happen if some project using EBML would allocate an Element ID for usage in the header that is already in use by another project using EBML? Specifically, what would hinder somebody from allocating 0x23E383 that Matroska uses for its `DefaultDuration`? RFC 8126 says that first-come-first-served registrations need to retain compability with the current usage of a codepoint, but how should the registration authority check this? All they have is the list of already registered elements (that only contains elements in the EBML Header). Then an EBML reader for the other project (in my example Matroska) would have two EBML elements with the same ID (0x23E383), one only valid in the `EBML Header`, the other valid only in (a part of) the `EBML Body` of an EBML file with appropriate DocType. I think that such a situation should be avoided and see two possibilities to do so:

- Check whether an Element ID is already in use by any user of EBML. This is akin to creating a central registry of codepoints already in use in any project. Of course, it would still be permitted for any two projects to use the same Element IDs for different elements in their own project, but any Element ID in use by any project would have to be distinct from any Element ID registered for usage in the EBML Header. This approach has two drawbacks: It has more administrative overhead and it might be possible that all short elements (say, all Element IDs of length two or less) will someday be in use in any project and therefore no longer available for use in the header, even when each of these projects uses only a fraction of these short Element IDs.
- Reserve certain ranges for future header elements. These ranges would of course need to be choosen in such a way as not to conflict with existing Matroska/Webm elements. Each project is free to use the remaining elements as it sees fit. This would adversly affect the ability to choose an arbitrary Element ID (if one wants to have a four byte Element ID with a nice ASCII representation or some other properties (CRC or so)).

I prefer the second option. What do you think?

**Comment by mkver** [comment]
Oh, and I don't think that any more one-octet Element IDs (besides void and crc) should be reserved.

**Comment by mcr** [comment]
This discussion needs to happen on the mailing list please.

**Comment by robUx4** [comment]
IMO that's a non-issue. As said on the ML they are different name spaces (and different IANA registry for a reason). If they collide it's not a problem since they can't be found in the same name spaces. If an EBML parser reading IDs doesn't try to match it within its allowed path, I think it's an issue in the parser, not the spec.

I'll leave it open for now in case some other issues regarding this are raised.

**Comment by robUx4** [comment]
Closing for now.
