### ISSUE TITLE
How complex can default values be?

### ISSUE THREAD

**Issue by mkver** [cellar-wg/ebml-specification#224]
The Matroska specification contains the following elements whose default values are not simply constants, but depend on other elements:

- `BlockDuration`: It's default value is `DefaultDuration`.
- `DisplayWidth` and `DisplayHeight`: The default value is `PixelWidth - PixelCropLeft - PixelCropRight` resp. `PixelHeight - PixelCropTop - PixelCropBottom`.
- `OutputSamplingFrequency`: It's default value is `SamplingFrequency`.

None of the above elements are currently mandatory (although the description of `BlockDuration` says that it is if `DefaultDuration` set), but the default value needs nevertheless to be evaluated if these elements are coded as empty elements. This raises the question as to how complicated the rules for default values are allowed to be. Constant values (and by these I mean constexpr) are of course possible and easy to implement, but how should an `EBML Reader` make sense of such complicated rules? In case of `BlockDuration` this implies to know the internals of the payload of the `Block` structure, although said payload is supposed to be a binary blob for the `EBML Reader` (although it's not a problem for the integrated EBML+Matroska reader that are currently in use).

I therefore propose to clarify the EBML specification to disallow non-constexpr values for default values and add a note stating that it is of course possible to include more complex rules for de-facto default values outside of the EBML layer.

Of course, the Matroska specification will have to be updated accordingly.

**Comment by robUx4** [comment]
This is a real issue. Right now there is no restrictions on what can be put in the `default` attribute of each element (nor in `size`, `label`). That should be fixed.

As for how to interpret the value we could define a syntax but that would take forever and block this document. I think it's a good thing that default values may be very complex things depending on the context (Matroska can't do without). We need to keep this possibility.

For machine readable purposes it's important that the Schema says if an element has a default value or not even if the value is not interepreted. For example in `mkvalidator` it allows checking things are correct or missing, without having to know if the context is legit.

I think escaping the `default` value when it's not a direct value could work. Another way would be to add an extra attribute for which the `default` value cannot be interpreted as such.

In Matroska there is:

- BlockDuration using `DefaultDuration`
- DisplayWidth using `PixelWidth - PixelCropLeft - PixelCropRight`
- DisplayHeight using `PixelHeight - PixelCropTop - PixelCropBottom`
- OutputSamplingFrequency using `SamplingFrequency`

**Comment by mkver** [comment]
> 
> As for how to interpret the value we could define a syntax but that would take forever and block this document. I think it's a good thing that default values may be very complex things depending on the context (Matroska can't do without). We need to keep this possibility.

I agree, but before we talk about how to store the default value we should clarify where to draw the line: It is clear that an EBML-only reader (that uses Matroska's EBML Schema) will never ever be able to evaluate the default value of `BlockDuration` as this requires parsing the `Block` structure (to get the TrackNumber) although a `Block` is a binary blob for an EBML reader. So this default element will have to be handled at a higher level (at the Matroska layer). If you want to have the information about the existence of a default value in EBML, then one would need to add a stub EBML value.

But the other values would be possible in EBML as these are of the form "The default value is the value of another element (of the same type) that is a sibling to the current element". (Said other element would have to be mandatory for this to work.) I think it would be good to have such a possibility in pure EBML. What do you think?

(One could easily extend this to "The default value is the value of a function whose return type is the same as the said element) whose parameters are other elements that are siblings to the current element." (One could also relax the sibling requirement.) But defining the syntax for functions etc. would really delay this document as you already remarked. Therefore we leave this topic to future extensions of the standard.)

**Comment by robUx4** [comment]
> > As for how to interpret the value we could define a syntax but that would take forever and block this document. I think it's a good thing that default values may be very complex things depending on the context (Matroska can't do without). We need to keep this possibility.
> 
> I agree, but before we talk about how to store the default value we should clarify where to draw the line: It is clear that an EBML-only reader (that uses Matroska's EBML Schema) will never ever be able to evaluate the default value of `BlockDuration` as this requires parsing the `Block` structure (to get the TrackNumber) although a `Block` is a binary blob for an EBML reader. So this default element will have to be handled at a higher level (at the Matroska layer). If you want to have the information about the existence of a default value in EBML, then one would need to add a stub EBML value.

This is a good point. Values that require parsing a `Binary Element` element can never be set explicitly. There should be a way to tell there's a default value though (to know if a mandatory element can be omitted).

I suggest separating the `default` attribute which has a usable value and a `default_extended` which would add non machine readable explanation about the default value. Both would signal there's a default value for the element.

I think escaping the non-machine readable it going to cause problem because we can never define a proper escaping system that won't collide with actual values some format may want to use.
 
> But the other values would be possible in EBML as these are of the form "The default value is the value of another element (of the same type) that is a sibling to the current element" ([Edit]: This is wrong. `DisplayWidth` and `DisplayHeight` aren't of this form, they are of the form mentioned below.). (Said other element would have to be mandatory for this to work.) I think it would be good to have such a possibility in pure EBML. What do you think?

Yes, it could be a path to the element whose value to copy. But it means you have to make sure they have a parent in common and that value is unique in that parent. While this is good I think this can be added later. Maybe in `default_extended`.

> (One could easily extend this to "The default value is the value of a function whose return type is the same as the said element) whose parameters are other elements that are siblings to the current element." (One could also relax the sibling requirement.) But defining the syntax for functions etc. would really delay this document as you already remarked. Therefore we leave this topic to future extensions of the standard and just leave a stub in the EBML Schema so that tools like mkvalidator can see that there is a default value, but that this default value needs to be evaluated at a higher level.)

**Comment by dericed** [comment]
Just noting that some related work to this issue is within https://github.com/cellar-wg/matroska-specification/pull/272. In general the attributes do not allow much complexity at all, but greater complexity may be expressed in an implementation_note. Still we need to say that more cleared in here.
