### ISSUE TITLE
Remove the IANA registries

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/ebml-specification#236]
If we consider we design EBML only for Matroska (for now or forever) we may not need the IANA registries at all. We just need to document the 2 existing DocType (`matroska` and `webm`).

For EBML IDs we can always create new documents to define them with their path in the header. We probably don't need a registry for that either.

This might lower the scrutiny needed to get the EBML spec through (although we do want to have it as clean as possible).

Reported-By: Robert Sparks <rjsparks@nostrum.com>

**Comment by mcr** [comment]
I think we should keep the IANA registry here.
