### ISSUE TITLE
Define the CRC-32 Element earlier in the document

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/ebml-specification#239]
Reported-By: Robert Sparks <rjsparks@nostrum.com>

**Comment by robUx4** [comment]
I'd rather move the paragraphs `Terminating Elements` and `Guidelines for Updating Elements` after the elements are actually defined. Probably after `Considerations for Reading EBML Data`.

**Comment by dericed** [comment]
resolved by https://github.com/cellar-wg/ebml-specification/pull/256?

**Comment by robUx4** [comment]
Not per se, but the flow is better IMO.
I suggest we close it and reopen if anyone complains.
