### ISSUE TITLE
clarity eneded for security statement

### ISSUE THREAD

**Issue by dericed** [cellar-wg/ebml-specification#268]
From Alexey Melnikov's review at https://mailarchive.ietf.org/arch/msg/cellar/CKtsS4agC5TT0VCCWlWMjzY7Y0k.

> 16.  Security Considerations
>
>  An EBML Reader MAY use the data if it considers it doesn't create any
>  security issue.

Alexey: I don't understand what this is trying to convey and how it can be complied with. Can you elaborate?
Alexey: I suggest just deleting this sentence.

Ping to Steve. This line was initially added in https://github.com/cellar-wg/ebml-specification/commit/640fbb71fb102f73948857bd97f7330d237bd5d6.

**Comment by robUx4** [comment]
I suppose it can be removed since we have detailed the possible security issues and their seriousness.

**Comment by retokromer** [comment]
+1
