### ISSUE TITLE
To generic or not to generic

### ISSUE THREAD

**Issue by robUx4** [cellar-wg/ebml-specification#304]
As per [Robert Sparks review](https://mailarchive.ietf.org/arch/msg/cellar/mlXwL0BuYcw6SlHWdlSSvBcvaLU), we may or may not make EBML a generic format usable by others than Matroska. If so we don't even need a IANA registry.

We need to take a definitive choice. If we go the generic way there might need more scrutiny from further people before we can publish. If not it doesn't mean that noone can use EBML for other things (and some already do).

I don't have a strong opinion on either way.

**Comment by dericed** [comment]
scrutiny isn't necessarily a negative thing for such a project. IIUC the decision for EBML to be generic was taken long ago. I'm not sure if reversing that decision is worth a short-time amount of expedience.

**Comment by retokromer** [comment]
I am in favour of EBML being a generic format.

**Comment by robUx4** [comment]
@mcr opinion on this ?

**Comment by robUx4** [comment]
I would also be happy that EBML is more generic, especially as we know other people are already using it, but maybe we're crossing the boundaries of the IETF workgroup that was defined.

**Comment by mcr** [comment]
I am in favour of EBML being defined as a generic archival format for multimedia content.
(Please note the qualifiers after the word generic).
I do not agree with Robert: we should create the IANA Registries.

Other wording: "multi-purpose archival format for multimedia content"

**Comment by dericed** [comment]
Just noting that EBML's own generic example is a simple wrapper for files, see https://www.ietf.org/id/draft-ietf-cellar-ebml-13.html#name-ebml-schema-example, which is not a "multi-purpose archival format for multimedia content".

**Comment by robUx4** [comment]
> 
> 
> Just noting that EBML's own generic example is a simple wrapper for files, see https://www.ietf.org/id/draft-ietf-cellar-ebml-13.html#name-ebml-schema-example, which is not a "multi-purpose archival format for multimedia content".

Just rename `File` to `MultimediaFile` :D

**Comment by mcr** [comment]
"generic archival format for multimedia content"

**Comment by midn1** [comment]
As someone who's invested enough time into Matroska and, by extension, EBML, and is looking to use EBML for something else, I'd like some clarification.

I don't understand the purpose of separating Matroska from EBML if in the end the intent is to support EBML only for multimedia content. Am I reading this correctly? If I am to use EBML to define, say, a custom executable format, or, hell, a state of the art digital cooking recipe format, I will be alone?

**Comment by midn1** [comment]
As someone who's invested enough time into Matroska and, by extension, EBML, and is looking to use EBML for something else, I'd like some clarification.

I don't understand the purpose of separating Matroska from EBML if in the end the intent is to support EBML only for multimedia content. Matroska in itself is so ~~bloated~~ featureful I have a hard time believing anyone would bother with EBML should they decide to start over.

So am I reading this correctly? If I am to use EBML to define, say, a custom executable format, or a state of the art digital cooking recipe format, I will be alone?

**Comment by robUx4** [comment]
RFC 8794 which is the EBML RFC, states

```
The goal of this document is to define a generic, binary, space-
   efficient format that can be used to define more complex formats
   using an EBML Schema.  EBML is used by the multimedia container,
   Matroska [Matroska].  The applicability of EBML for other use cases
   is beyond the scope of this document.
```

It is totally usable for other things and we know some people do. And that's why EBML is separated from Matroska (and it's also used in WebM which has a different DocType). Even libebml and libmatroska are split.

**Comment by JeromeMartinez** [comment]
> If I am to use EBML to define, say, a custom executable format, or a state of the art digital cooking recipe format, I will be alone?

I use it in [RAWcooked](https://github.com/MediaArea/RAWcooked) for the reversibility file (stored data is file names, file hashes, mask between source file and encoded pictures, etc) and it is not based on Matroska.

**Comment by midn1** [comment]
I've come to distrust formal statements like RFCs, so I looked here, and was confused by the contradicting opinions. Either way, thank you.
