### ISSUE TITLE
XHTML Basic has been superseded

### ISSUE THREAD

**Issue by retokromer** [cellar-wg/ebml-specification#341]
As noted in https://github.com/cellar-wg/ebml-specification/pull/340#pullrequestreview-418908133, W3C’s [XHTML Basic](https://www.w3.org/TR/xhtml-basic/) recommendation has been superseded on 27 March 2018, therefore – in my opinion – a valid reference should be used instead.

**Comment by robUx4** [comment]
What do you recommend replacing it with ? The [20180327 document](https://www.w3.org/TR/2018/SPSD-xhtml-basic-20180327/) doesn't mention what it's been superseded by. And I can't find anything online about it.
IMO it's ok to keep the reference. The standard is not going away even if it's deprecated. In 20 years all the reference in our RFC might be supersed, that doesn't make the document invalid or use missing reference (unless with proprietary "standards").

**Comment by retokromer** [comment]
>The standard is not going away even if it's deprecated.

That’s true. Nevertheless, I would personally prefer current ones, but it’s not up to me to decide.

Internally we work currently with HTML 5.2 which allows both syntaxes HTML and XML (XHTML).

**Comment by retokromer** [comment]
I see now that W3C released also [HTML 5.3](https://www.w3.org/TR/html53/) and that they switched to a [HTML living standard](https://html.spec.whatwg.org/).

**Comment by robUx4** [comment]
This is tricky. It seems the XHTML spec is merged into HTML with the following difference:

>The second concrete syntax is the XHTML syntax, which is an application of XML. When a document is transmitted with an XML MIME type, such as application/xhtml+xml, then it is treated as an XML document by Web browsers, to be parsed by an XML processor. Authors are reminded that the processing for XML and HTML differs; in particular, even minor syntax errors will prevent a document labeled as XML from being rendered fully, whereas they would be ignored in the HTML syntax. This specification defines the latest version of the XHTML syntax, known simply as "XHTML".

And also

> The DOM, the HTML syntax, and the XHTML syntax cannot all represent the same content. For example, namespaces cannot be represented using the HTML syntax, but they are supported in the DOM and in the XHTML syntax.

So we should mention that the HTML tags are to be parsed as XHTML with the XHTML namespace. That seems a rather complex thing just to switch to a spec that was supersed (merged) 2 years ago.

**Comment by robUx4** [comment]
I think so. Also the RFC is published, I'm not sure we'll ever make any edit to it. Or with a brand new document.
